name: Testing Workflow 2

on: [push]

jobs:
  build-project-for-roland: 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "22"

      - name: Install Dependencies
        run: npm ci

      - name: Run tests
        run: npm test
